# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pbcopy

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Pastebuffer pbcopy
Version:    1.3
Release:    1
Group:      Qt/Qt
License:    GPLv2
URL:        https://particolarmente-urgentissimo.blogspot.com
Source0:    %{name}-%{version}.tar.bz2
Source100:  pbcopy.yaml
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.9
BuildRequires:  pkgconfig(Qt5Core)

%description
Copy text from/to Qt pastebuffer via stdin/stdout


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    APPNAME='%{name}' \
    VERSION='%{version}-%{release}' \
    AUTHOR='Alfonso_Martone'

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/icons/hicolor/86x86/apps/icon86.png
%{_datadir}/icons/hicolor/108x108/apps/icon108.png
%{_datadir}/icons/hicolor/128x128/apps/icon128.png
%{_datadir}/icons/hicolor/256x256/apps/icon256.png
# >> files
# << files
